print('---------------------将其他类型转换成str-------------------------')
a=38
b=250
c=True
print(type(a),type(b),type(c))
print('\n')
print(str(a),str(a),str(c),type(str(a)),type(str(b)),type(str(c)))
print("------------------------int型转换----------------------------")
print()